apiVersion: v1
kind: Service
metadata:
  name: mcp-server-svc
  namespace: mcp-server
  labels:
    app: mcp-azure-devops
spec:
  type: LoadBalancer
  selector:
    app: mcp-azure-devops
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
