apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-server-sa
  namespace: mcp-server
  annotations:
    # Workload Identity — links this K8s SA to an Azure Managed Identity
    azure.workload.identity/client-id: "2d003cd3-1822-4e94-8697-ed6b2e8b0482"
  labels:
    azure.workload.identity/use: "true"
