apiVersion: v1
kind: Secret
metadata:
    name: sops-demo-secret
    namespace: flux-system
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:0nGKd1k=,iv:Ihm0VaOmiImjpgU5dqauhSJEEEyv+3jwyajN2HUL9cw=,tag:wDzIqcAnknQ0cWGTagywdg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:CPUTVqXDd8QU7n1TSEi3,iv:IS2Hu7nFDu43RN0bGCLXbTGcBcPhCT9WM7aTWxL1+2E=,tag:aI7WmXkJ5qtj3ZpTb+/C+A==,type:str]
    API_KEY: ENC[AES256_GCM,data:SRiLVDkKhbDwlfmMRbdaU7I=,iv:0EEJydn1XwDEjqLYLa2/K+yk2muw1j/RMz2k/ycKrgE=,tag:7V6eC5C8yANKaG7xX/xg/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://midodevops-test.vault.azure.net
          name: sops-terraform
          version: cd171914eac24937b3877c6196457ce2
          created_at: "2026-04-26T06:16:43Z"
          enc: BV0PlHA7LYxE-YGd67sj5YUQVWte53O6H6q3-G6s3aUoG3R1k9Gh4hogV_AI3OCAuhhdWANg5ao4xG0HwMMd50raYtJRO8AtG7dGPuisBuOw5JF3S6lae1CyIuLG6gVpDccbr4i01oSnyxeSG2g1ny4HQY49Q4aC24mMUtiwAwIUUt0dliFYgwPk5I2T_v0zRqqjPJJ0xfrr9CTMh8VFOK-VeuJolXPCsqpmvFLcsrZW0-3VDOU5mOp66pk_F7usqFwx-up84ot6OHfb3p9KCxl4zwzVqekJaM37i-9ZnI1qRQtcvh8DC9OvF6AjiiGxqBxhf0x7l7o-9-tjCuTrGQ
    hc_vault: []
    age: []
    lastmodified: "2026-04-26T06:16:46Z"
    mac: ENC[AES256_GCM,data:pzyGiupLNuTwIcAwbDVB0gHcz732eJZlucLT79eM36KosPNEDeVxzSmKcDlqbe7mfSwuhQl+8PFkirNlSmOnicILsox3QvBpHRk0xPb0Vm9yi52n1QFTrA7dPYQVV8DC64lp7AAqNmjrlWit6+Eo5FXnhp3yfiSMcbHEBeRhpoM=,iv:yMDQEIgRXF8XViOI225iyxuR1Y0FWnGxRh4p7XoiLGw=,tag:kL5NfxyZvXADE15tL8oLhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
